site_name: Dipayan Chattopadhyay
site_url: https://dipayan90.github.io
repo_url: https://github.com/dipayan90/dipayan90.github.io
repo_name: Edit Me
edit_uri: edit/master/docs/
docs_dir: documentation

nav:
  - Connect: index.md
  - Introduction: summary.md
  - Experience: experience.md
  - OpenSource: opensource.md
  - Skills: skills.md
  - Miscellaneous: miscellaneous.md

theme: material