site_name: Dipayan Chattopadhyay
site_url: https://dipayan90.github.io
repo_url: https://github.com/dipayan90/dipayan90.github.io
repo_name: Abour Dipayan
docs_dir: docs/

nav:
  - Connect: index.md
  - Introduction: summary.md
  - Experience: experience.md
  - OpenSource: opensource.md
  - Skills: skills.md
  - Miscellaneous: miscellaneous.md

theme: material